In [7]:
import pandas as pd

In [8]:
dataset = pd.read_csv("Wine.csv")

In [9]:
dataset

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline  Customer_Segment  
0     3.92     1065                 1  
1     3.40     1050                 1  
2     3.17     1185                 1  
3     3.45     1480                 1  
4     2.93      735                 1  
..     ...      ...               ...  
173   1.74      740                 3  
174   1.56      750                 3  
175   1.56      835                 3  
176   1.62      840                 3  
177   1.60      560                 3  

[178 rows x 14 columns]

In [10]:
X = dataset.iloc[:,:-1].values

In [11]:
y = dataset.iloc[:,-1].values

In [12]:
X

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [13]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3], dtype=int64)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [16]:
X_train

array([[1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       [1.208e+01, 2.080e+00, 1.700e+00, ..., 1.270e+00, 2.960e+00,
        7.100e+02],
       [1.242e+01, 4.430e+00, 2.730e+00, ..., 9.200e-01, 3.120e+00,
        3.650e+02],
       ...,
       [1.438e+01, 1.870e+00, 2.380e+00, ..., 1.200e+00, 3.000e+00,
        1.547e+03],
       [1.269e+01, 1.530e+00, 2.260e+00, ..., 9.600e-01, 2.060e+00,
        4.950e+02],
       [1.234e+01, 2.450e+00, 2.460e+00, ..., 8.000e-01, 3.380e+00,
        4.380e+02]])

In [17]:
y_train

array([1, 2, 2, 3, 1, 2, 1, 1, 3, 3, 2, 2, 1, 2, 1, 3, 2, 2, 3, 1, 1, 1,
       3, 1, 1, 2, 3, 2, 1, 3, 2, 1, 3, 2, 2, 1, 2, 1, 1, 2, 1, 1, 3, 2,
       2, 2, 1, 2, 2, 2, 3, 3, 1, 2, 3, 3, 2, 2, 1, 2, 3, 3, 2, 3, 2, 2,
       2, 1, 1, 3, 1, 3, 1, 1, 2, 2, 1, 1, 1, 2, 1, 2, 3, 2, 2, 2, 3, 3,
       2, 1, 1, 2, 3, 3, 1, 2, 3, 3, 3, 3, 2, 1, 2, 1, 3, 1, 1, 2, 1, 1,
       3, 2, 1, 3, 3, 1, 1, 3, 3, 3, 2, 2, 2, 2, 2, 2, 3, 1, 2, 2, 1, 2,
       2], dtype=int64)

In [18]:
X_test

array([[1.364000e+01, 3.100000e+00, 2.560000e+00, 1.520000e+01,
        1.160000e+02, 2.700000e+00, 3.030000e+00, 1.700000e-01,
        1.660000e+00, 5.100000e+00, 9.600000e-01, 3.360000e+00,
        8.450000e+02],
       [1.421000e+01, 4.040000e+00, 2.440000e+00, 1.890000e+01,
        1.110000e+02, 2.850000e+00, 2.650000e+00, 3.000000e-01,
        1.250000e+00, 5.240000e+00, 8.700000e-01, 3.330000e+00,
        1.080000e+03],
       [1.293000e+01, 2.810000e+00, 2.700000e+00, 2.100000e+01,
        9.600000e+01, 1.540000e+00, 5.000000e-01, 5.300000e-01,
        7.500000e-01, 4.600000e+00, 7.700000e-01, 2.310000e+00,
        6.000000e+02],
       [1.373000e+01, 1.500000e+00, 2.700000e+00, 2.250000e+01,
        1.010000e+02, 3.000000e+00, 3.250000e+00, 2.900000e-01,
        2.380000e+00, 5.700000e+00, 1.190000e+00, 2.710000e+00,
        1.285000e+03],
       [1.237000e+01, 1.170000e+00, 1.920000e+00, 1.960000e+01,
        7.800000e+01, 2.110000e+00, 2.000000e+00, 2.700000e-01,
        1.04

In [19]:
y_test

array([1, 1, 3, 1, 2, 1, 2, 3, 2, 3, 1, 3, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2,
       2, 3, 3, 3, 2, 2, 2, 1, 1, 2, 3, 1, 1, 1, 3, 3, 2, 3, 1, 2, 2, 2,
       3], dtype=int64)

In [20]:
from sklearn.preprocessing import StandardScaler
sc =  StandardScaler()

In [21]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [22]:
X_train

array([[ 2.26327625e-01, -2.45185855e-02,  1.10112749e+00, ...,
         3.01960239e-01,  7.70065176e-01,  1.44583084e+00],
       [-1.07980737e+00, -2.80281086e-01, -2.36874201e+00, ...,
         1.32908842e+00,  4.81290735e-01, -1.07920216e-01],
       [-6.68616724e-01,  1.86629704e+00,  1.31575859e+00, ...,
        -1.68806843e-01,  7.01309357e-01, -1.23643414e+00],
       ...,
       [ 1.70177642e+00, -4.72102961e-01,  6.37438239e-02, ...,
         1.02950937e+00,  5.36295390e-01,  2.62995270e+00],
       [-3.42082975e-01, -7.82671711e-01, -3.65518382e-01, ...,
         2.38118688e-03, -7.56314012e-01, -8.11197011e-01],
       [-7.65367464e-01,  5.76907895e-02,  3.49918628e-01, ...,
        -6.82370932e-01,  1.05883962e+00, -9.97647138e-01]])

In [23]:
X_test

array([[ 8.06832067e-01,  6.51425164e-01,  7.07637133e-01,
        -1.22568751e+00,  1.01991065e+00,  6.57478171e-01,
         1.00703506e+00, -1.53058075e+00,  8.93427142e-02,
         3.75559480e-02,  2.38118688e-03,  1.03133729e+00,
         3.33672190e-01],
       [ 1.49618109e+00,  1.51005641e+00,  2.78374927e-01,
        -1.54544155e-01,  6.85307503e-01,  8.90663763e-01,
         6.27698755e-01, -5.02463378e-01, -6.23960098e-01,
         1.01359940e-01, -3.82791880e-01,  9.90083798e-01,
         1.10237008e+00],
       [-5.18307538e-02,  3.86528289e-01,  1.20844304e+00,
         4.53402076e-01, -3.18501945e-01, -1.14582374e+00,
        -1.51854612e+00,  1.31651351e+00, -1.49384158e+00,
        -1.90315452e-01, -8.10761955e-01, -4.12534916e-01,
        -4.67736251e-01],
       [ 9.15676650e-01, -8.10074836e-01,  1.20844304e+00,
         8.87649384e-01,  1.61012042e-02,  1.12384935e+00,
         1.22665081e+00, -5.81549330e-01,  1.34197204e+00,
         3.11001628e-01,  9.86712358e

In [68]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 2)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

In [69]:
X_train

array([[-3.47394102,  1.28317488],
       [-1.00866616, -3.14403965],
       [ 0.61148467, -2.36399247],
       [ 4.58803858,  0.25153043],
       [-4.44446856,  1.95083446],
       [ 0.21742172, -2.53870924],
       [-2.86618685,  1.84988059],
       [-4.13805606,  2.33681131],
       [ 5.13923669,  2.53925366],
       [ 3.56235065,  1.00323368],
       [-1.14714765, -2.62442518],
       [-0.71489964, -2.06559108],
       [-2.89700342,  2.01605786],
       [-0.68372301, -3.00477675],
       [-4.93105316,  0.68305804],
       [ 4.6237411 ,  1.56172473],
       [-1.05645855, -3.05979066],
       [-0.16077057, -3.09434791],
       [ 5.22709999,  2.37489248],
       [-3.47731777,  2.03539914],
       [-4.66124994,  3.08340059],
       [-2.76263693,  1.10143733],
       [ 3.82311727,  1.79038743],
       [-1.53616583,  0.63220528],
       [-3.41411557,  0.22893595],
       [-1.54980528, -2.14787877],
       [ 4.00075564,  0.39561758],
       [ 1.14431827, -2.87762419],
       [-4.76691951,

In [70]:
from sklearn.linear_model import LogisticRegression as LR
lr = LR()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

In [71]:
y_test

array([1, 1, 3, 1, 2, 1, 2, 3, 2, 3, 1, 3, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2,
       2, 3, 3, 3, 2, 2, 2, 1, 1, 2, 3, 1, 1, 1, 3, 3, 2, 3, 1, 2, 2, 2,
       3], dtype=int64)

In [72]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[15,  0,  0],
       [ 1, 17,  0],
       [ 0,  0, 12]], dtype=int64)

In [73]:
from sklearn.metrics import accuracy_score

In [74]:
accuracy_score(y_test, y_pred)

0.9777777777777777

In [75]:
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import numpy as np

In [16]:
X_set, y_set = X_train, y_train
X1, X2 = np.meshgrid(
            np.arange(start = X_set[:,0].min()-1, stop = X_set[:,0].max()+1, step = 0.25),
            np.arange(start = X_set[:,1].min()-1, stop = X_set[:,1].max()+1, step = 0.25)
                )
plt.contourf(X1, X2, lr.predict(np.array[X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
            alpha = 0.75, cmap = ListedColormap(('blue','red','green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X1.min(), X1.max())
    
for i,j in enumerate(np.unique(y_set)):
        plt.scatter(X_set[y_set == j, 0], X_set[y_set == j,1])
                   c = ListedColormap(('blue','red','green))(i), label = j)

IndentationError: unexpected indent (4129962923.py, line 7)